a1= input("Number 1= ")
a2= input("Number 2 = ")
a1=int(a1)
a2=int(a2)
print("Addition = ",a1+a2)
print("Subtraction = ",a1-a2)
print("Multiplication = ",a1*a2)
print("Division = ",a1/a2)
print("Thankyou")